DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
  id       BIGINT          AUTO_INCREMENT,
  username VARCHAR(100),
  password VARCHAR(100),
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS role;

CREATE TABLE ROLE
(
  id   BIGINT       AUTO_INCREMENT,
  role VARCHAR(250),
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS user_roles;

CREATE TABLE USER_ROLES (
  user_id BIGINT,
  role_id BIGINT,
  FOREIGN KEY (role_id) REFERENCES ROLE (id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (user_id) REFERENCES USER (id) ON DELETE CASCADE ON UPDATE CASCADE
);

