insert into business_type(code_kved, title) values(01, "Сільське господарство, мисливство та надання пов'язаних із ними послуг");
insert into business_type(code_kved, title) values(01.1, "Вирощування однорічних і дворічних культур");
insert into business_type(code_kved, title) values(01.2, "Вирощування багаторічних культур");
insert into business_type(code_kved, title) values(01.4, "Тваринництво");
insert into business_type(code_kved, title) values(01.6, "Допоміжна діяльність у сільському господарстві та післяурожайна діяльність");
insert into business_type(code_kved, title) values(02, "Лісове господарство та лісозаготівлі");
insert into business_type(code_kved, title) values(02.1, "Лісівництво та інша діяльність у лісовому господарстві");
insert into business_type(code_kved, title) values(02.2, "Лісозаготівлі");
insert into business_type(code_kved, title) values(02.3, "Збирання дикорослих недеревних продуктів");
insert into business_type(code_kved, title) values(02.4, "Надання допоміжних послуг у лісовому господарстві");
insert into business_type(code_kved, title) values(03, "Рибне господарство");
insert into business_type(code_kved, title) values(03.1, "Рибальство");
insert into business_type(code_kved, title) values(03.2, "Рибництво (аквакультура)");
insert into business_type(code_kved, title) values(05, "Добування кам'яного та бурого вугілля");
insert into business_type(code_kved, title) values(05.1, "Добування кам'яного вугілля");
insert into business_type(code_kved, title) values(05.2, "Добування бурого вугілля");
insert into business_type(code_kved, title) values(06, "Добування сирої нафти та природного газу");
insert into business_type(code_kved, title) values(06.1, "Добування сирої нафти");
insert into business_type(code_kved, title) values(06.2, "Добування природного газу");
insert into business_type(code_kved, title) values(07, "Добування металевих руд");
insert into business_type(code_kved, title) values(07.1, "Добування залізних руд");
insert into business_type(code_kved, title) values(07.2, "Добування руд кольорових металів");
insert into business_type(code_kved, title) values(08, "Добування інших корисних копалин і розроблення кар'єрів");
insert into business_type(code_kved, title) values(08.1, "Добування каменю, піску та глини");
insert into business_type(code_kved, title) values(08.9, "Добування корисних копалин і розроблення кар'єрів, н. в. і. у.");
insert into business_type(code_kved, title) values(09, "Надання допоміжних послуг у сфері добувної промисловості та розроблення кар'єрів");
insert into business_type(code_kved, title) values(09.1, "Надання допоміжних послуг у сфері добування нафти та природного газу");
insert into business_type(code_kved, title) values(09.9, "Надання допоміжних послуг у сфері добування інших корисних копалин і розроблення кар'єрів");
insert into business_type(code_kved, title) values(01.11, "Вирощування зернових культур (крім рису), бобових культур і насіння олійних культур");
insert into business_type(code_kved, title) values(01.12, "Вирощування рису");
insert into business_type(code_kved, title) values(01.13, "Вирощування овочів і баштанних культур, коренеплодів і бульбоплодів");
insert into business_type(code_kved, title) values(01.14, "Вирощування цукрової тростини");
insert into business_type(code_kved, title) values(01.15, "Вирощування тютюну");
insert into business_type(code_kved, title) values(01.16, "Вирощування прядивних культур");
insert into business_type(code_kved, title) values(01.19, "Вирощування інших однорічних і дворічних культур");
insert into business_type(code_kved, title) values(01.21, "Вирощування винограду");
insert into business_type(code_kved, title) values(01.22, "Вирощування тропічних і субтропічних фруктів");
insert into business_type(code_kved, title) values(01.23, "Вирощування цитрусових");
insert into business_type(code_kved, title) values(01.24, "Вирощування зерняткових і кісточкових фруктів");
insert into business_type(code_kved, title) values(01.25, "Вирощування ягід, горіхів, інших фруктів");
insert into business_type(code_kved, title) values(01.26, "Вирощування олійних плодів");
insert into business_type(code_kved, title) values(01.27, "Вирощування культур для виробництва напоїв");
insert into business_type(code_kved, title) values(01.28, "Вирощування пряних, ароматичних і лікарських культур");
insert into business_type(code_kved, title) values(01.29, "Вирощування інших багаторічних культур");
insert into business_type(code_kved, title) values(01.3, "Відтворення рослин");
insert into business_type(code_kved, title) values(01.41, "Розведення великої рогатої худоби молочних порід");
insert into business_type(code_kved, title) values(01.42, "Розведення іншої великої рогатої худоби та буйволів");
insert into business_type(code_kved, title) values(01.43, "Розведення коней та інших тварин родини конячих");
insert into business_type(code_kved, title) values(01.44, "Розведення верблюдів та інших тварин родини верблюдячих");
insert into business_type(code_kved, title) values(01.45, "Розведення овець і кіз");
insert into business_type(code_kved, title) values(01.46, "Розведення свиней");
insert into business_type(code_kved, title) values(01.47, "Розведення свійської птиці");
insert into business_type(code_kved, title) values(01.49, "Розведення інших тварин");
insert into business_type(code_kved, title) values(01.5, "Змішане сільське господарство");
insert into business_type(code_kved, title) values(01.61, "Допоміжна діяльність у рослинництві");
insert into business_type(code_kved, title) values(01.62, "Допоміжна діяльність у тваринництві");
insert into business_type(code_kved, title) values(01.63, "Післяурожайна діяльність");
insert into business_type(code_kved, title) values(01.64, "Оброблення насіння для відтворення");
insert into business_type(code_kved, title) values(01.7, "Мисливство, відловлювання тварин і надання пов'язаних із ними послуг");
insert into business_type(code_kved, title) values(10, "Виробництво харчових продуктів");
insert into business_type(code_kved, title) values(10.1, "Виробництво м'яса та м'ясних продуктів");
insert into business_type(code_kved, title) values(10.11, "Виробництво м'яса");
insert into business_type(code_kved, title) values(10.12, "Виробництво м'яса свійської птиці");
insert into business_type(code_kved, title) values(10.13, "Виробництво м'ясних продуктів");
insert into business_type(code_kved, title) values(10.2, "Перероблення та консервування риби, ракоподібних і молюсків");
insert into business_type(code_kved, title) values(10.3, "Перероблення та консервування фруктів і овочів");
insert into business_type(code_kved, title) values(10.31, "Перероблення та консервування картоплі");
insert into business_type(code_kved, title) values(10.32, "Виробництво фруктових і овочевих соків");
insert into business_type(code_kved, title) values(10.39, "Інші види перероблення та консервування фруктів і овочів");
insert into business_type(code_kved, title) values(10.41, "Виробництво олії та тваринних жирів");
insert into business_type(code_kved, title) values(10.42, "Виробництво маргарину і подібних харчових жирів");
insert into business_type(code_kved, title) values(10.5, "Виробництво молочних продуктів");
insert into business_type(code_kved, title) values(10.51, "Перероблення молока, виробництво масла та сиру");
insert into business_type(code_kved, title) values(10.52, "Виробництво морозива");
insert into business_type(code_kved, title) values(10.6, "Виробництво продуктів борошномельно-круп'яної промисловості, крохмалів і крохмальних продуктів");
insert into business_type(code_kved, title) values(10.61, "Виробництво продуктів борошномельно-круп'яної промисловості");
insert into business_type(code_kved, title) values(10.62, "Виробництво крохмалів і крохмальних продуктів");
insert into business_type(code_kved, title) values(10.7, "Виробництво хліба, хлібобулочних і борошняних виробів");
insert into business_type(code_kved, title) values(10.71, "Виробництво хліба та хлібобулочних виробів; виробництво борошняних кондитерських виробів, тортів і тістечок нетривалого зберігання");
insert into business_type(code_kved, title) values(10.72, "Виробництво сухарів і сухого печива; виробництво борошняних кондитерських виробів, тортів і тістечок тривалого зберігання");
insert into business_type(code_kved, title) values(10.73, "Виробництво макаронних виробів і подібних борошняних виробів");
insert into business_type(code_kved, title) values(10.8, "Виробництво інших харчових продуктів");
insert into business_type(code_kved, title) values(10.81, "Виробництво цукру");
insert into business_type(code_kved, title) values(10.82, "Виробництво какао, шоколаду та цукрових кондитерських виробів");
insert into business_type(code_kved, title) values(10.83, "Виробництво чаю та кави");
insert into business_type(code_kved, title) values(10.84, "Виробництво прянощів і приправ");
insert into business_type(code_kved, title) values(10.85, "Виробництво готової їжі та страв");
insert into business_type(code_kved, title) values(10.86, "Виробництво дитячого харчування та дієтичних харчових продуктів");
insert into business_type(code_kved, title) values(10.89, "Виробництво інших харчових продуктів, н. в. і. у.");
insert into business_type(code_kved, title) values(10.9, "Виробництво готових кормів для тварин");
insert into business_type(code_kved, title) values(10.91, "Виробництво готових кормів для тварин, що утримуються на фермах");
insert into business_type(code_kved, title) values(10.92, "Виробництво готових кормів для домашніх тварин");
insert into business_type(code_kved, title) values(11.01, "Дистиляція, ректифікація та змішування алкогольних напоїв");
insert into business_type(code_kved, title) values(11.02, "Виробництво виноградних вин");
insert into business_type(code_kved, title) values(11.03, "Виробництво сидру та інших плодово-ягідних вин");
insert into business_type(code_kved, title) values(11.04, "Виробництво інших недистильованих напоїв із зброджуваних продуктів");
insert into business_type(code_kved, title) values(11.05, "Виробництво пива");
insert into business_type(code_kved, title) values(11.06, "Виробництво солоду");
insert into business_type(code_kved, title) values(11.07, "Виробництво безалкогольних напоїв; виробництво мінеральних вод та інших вод, розлитих у пляшки");
insert into business_type(code_kved, title) values(12.0, "Виробництво тютюнових виробів");
insert into business_type(code_kved, title) values(13, "Текстильне виробництво");
insert into business_type(code_kved, title) values(13.1, "Підготування та прядіння текстильних волокон");
insert into business_type(code_kved, title) values(13.2, "Ткацьке виробництво");
insert into business_type(code_kved, title) values(13.3, "Оздоблення текстильних виробів");
insert into business_type(code_kved, title) values(13.9, "Виробництво інших текстильних виробів");
insert into business_type(code_kved, title) values(13.91, "Виробництво трикотажного полотна");
insert into business_type(code_kved, title) values(13.92, "Виробництво готових текстильних виробів, крім одягу");
insert into business_type(code_kved, title) values(13.93, "Виробництво килимів і килимових виробів");
insert into business_type(code_kved, title) values(13.94, "Виробництво канатів, мотузок, шпагату та сіток");
insert into business_type(code_kved, title) values(13.95, "Виробництво нетканих текстильних матеріалів і виробів із них, крім одягу");
insert into business_type(code_kved, title) values(13.96, "Виробництво інших текстильних виробів технічного та промислового призначення");
insert into business_type(code_kved, title) values(13.99, "Виробництво інших текстильних виробів, н. в. і. у.");
insert into business_type(code_kved, title) values(14, "Виробництво одягу");
insert into business_type(code_kved, title) values(14.1, "Виробництво одягу, крім хутряного");
insert into business_type(code_kved, title) values(14.11, "Виробництво одягу зі шкіри");
insert into business_type(code_kved, title) values(14.12, "Виробництво робочого одягу");
insert into business_type(code_kved, title) values(14.13, "Виробництво іншого верхнього одягу");
insert into business_type(code_kved, title) values(14.14, "Виробництво спіднього одягу");
insert into business_type(code_kved, title) values(14.19, "Виробництво іншого одягу й аксесуарів");
insert into business_type(code_kved, title) values(14.2, "Виготовлення виробів із хутра");
insert into business_type(code_kved, title) values(14.3, "Виробництво трикотажного та в'язаного одягу");
insert into business_type(code_kved, title) values(14.31, "Виробництво панчішно-шкарпеткових виробів");
insert into business_type(code_kved, title) values(14.39, "Виробництво іншого трикотажного та в'язаного одягу");
insert into business_type(code_kved, title) values(15, "Виробництво шкіри, виробів зі шкіри та інших матеріалів");
insert into business_type(code_kved, title) values(15.1, "Дублення шкур і оздоблення шкіри; виробництво дорожніх виробів, сумок, лимарно-сідельних виробів; вичинка та фарбування хутра");
insert into business_type(code_kved, title) values(15.11, "Дублення шкур і оздоблення шкіри; вичинка та фарбування хутра");
insert into business_type(code_kved, title) values(15.12, "Виробництво дорожніх виробів, сумок, лимарно-сідельних виробів зі шкіри та інших матеріалів");
insert into business_type(code_kved, title) values(15.2, "Виробництво взуття");
insert into business_type(code_kved, title) values(16, "Оброблення деревини та виготовлення виробів з деревини та корка, крім меблів; виготовлення виробів із соломки та рослинних матеріалів для плетіння");
insert into business_type(code_kved, title) values(16.1, "Лісопильне та стругальне виробництво");
insert into business_type(code_kved, title) values(16.2, "Виготовлення виробів з деревини, корка, соломки та рослинних матеріалів для плетіння");
insert into business_type(code_kved, title) values(16.21, "Виробництво фанери, дерев'яних плит і панелей, шпону");
insert into business_type(code_kved, title) values(16.22, "Виробництво щитового паркету");
insert into business_type(code_kved, title) values(16.23, "Виробництво інших дерев'яних будівельних конструкцій і столярних виробів");
insert into business_type(code_kved, title) values(16.24, "Виробництво дерев'яної тари");
insert into business_type(code_kved, title) values(16.29, "Виробництво інших виробів з деревини; виготовлення виробів з корка, соломки та рослинних матеріалів для плетіння");
insert into business_type(code_kved, title) values(17, "Виробництво паперу та паперових виробів");
insert into business_type(code_kved, title) values(17.1, "Виробництво паперової маси, паперу та картону");
insert into business_type(code_kved, title) values(17.11, "Виробництво паперової маси");
insert into business_type(code_kved, title) values(17.12, "Виробництво паперу та картону");
insert into business_type(code_kved, title) values(17.2, "Виготовлення виробів з паперу та картону");
insert into business_type(code_kved, title) values(17.21, "Виробництво гофрованого паперу та картону, паперової та картонної тари");
insert into business_type(code_kved, title) values(17.22, "Виробництво паперових виробів господарсько-побутового та санітарно-гігієнічного призначення");
insert into business_type(code_kved, title) values(17.23, "Виробництво паперових канцелярських виробів");
insert into business_type(code_kved, title) values(17.24, "Виробництво шпалер");
insert into business_type(code_kved, title) values(17.29, "Виробництво інших виробів з паперу та картону");
insert into business_type(code_kved, title) values(18, "Поліграфічна діяльність, тиражування записаної інформації");
insert into business_type(code_kved, title) values(18.1, "Поліграфічна діяльність і надання пов'язаних із нею послуг");
insert into business_type(code_kved, title) values(18.11, "Друкування газет");
insert into business_type(code_kved, title) values(18.12, "Друкування іншої продукції");
insert into business_type(code_kved, title) values(18.13, "Виготовлення друкарських форм і надання інших поліграфічних послуг");
insert into business_type(code_kved, title) values(18.14, "Брошурувально-палітурна діяльність і надання пов'язаних із нею послуг");
insert into business_type(code_kved, title) values(18.2, "Тиражування звуко-, відеозаписів і програмного забезпечення");
insert into business_type(code_kved, title) values(19, "Виробництво коксу та продуктів нафтоперероблення");
insert into business_type(code_kved, title) values(19.1, "Виробництво коксу та коксопродуктів");
insert into business_type(code_kved, title) values(19.2, "Виробництво продуктів нафтоперероблення");
insert into business_type(code_kved, title) values(20, "Виробництво хімічних речовин і хімічної продукції");
insert into business_type(code_kved, title) values(20.1, "Виробництво основної хімічної продукції, добрив і азотних сполук, пластмас і синтетичного каучуку в первинних формах");
insert into business_type(code_kved, title) values(20.11, "Виробництво промислових газів");
insert into business_type(code_kved, title) values(20.12, "Виробництво барвників і пігментів");
insert into business_type(code_kved, title) values(20.13, "Виробництво інших основних неорганічних хімічних речовин");
insert into business_type(code_kved, title) values(20.14, "Виробництво інших основних органічних хімічних речовин");
insert into business_type(code_kved, title) values(20.15, "Виробництво добрив і азотних сполук");
insert into business_type(code_kved, title) values(20.16, "Виробництво пластмас у первинних формах");
insert into business_type(code_kved, title) values(20.17, "Виробництво синтетичного каучуку в первинних формах");
insert into business_type(code_kved, title) values(20.2, "Виробництво пестицидів та іншої агрохімічної продукції");
insert into business_type(code_kved, title) values(20.3, "Виробництво фарб, лаків і подібної продукції, друкарської фарби та мастик");
insert into business_type(code_kved, title) values(20.4, "Виробництво мила та мийних засобів, засобів для чищення та полірування, парфумних і косметичних засобів");
insert into business_type(code_kved, title) values(20.41, "Виробництво мила та мийних засобів, засобів для чищення та полірування");
insert into business_type(code_kved, title) values(20.42, "Виробництво парфумних і косметичних засобів");
insert into business_type(code_kved, title) values(20.5, "Виробництво іншої хімічної продукції");
insert into business_type(code_kved, title) values(20.51, "Виробництво вибухових речовин");
insert into business_type(code_kved, title) values(20.52, "Виробництво клеїв");
insert into business_type(code_kved, title) values(20.53, "Виробництво ефірних олій");
insert into business_type(code_kved, title) values(20.59, "Виробництво іншої хімічної продукції, н. в. і. у.");
insert into business_type(code_kved, title) values(20.6, "Виробництво штучних і синтетичних волокон");
insert into business_type(code_kved, title) values(21, "Виробництво основних фармацевтичних продуктів і фармацевтичних препаратів");
insert into business_type(code_kved, title) values(21.1, "Виробництво основних фармацевтичних продуктів");
insert into business_type(code_kved, title) values(21.2, "Виробництво фармацевтичних препаратів і матеріалів");
insert into business_type(code_kved, title) values(22, "Виробництво гумових і пластмасових виробів");
insert into business_type(code_kved, title) values(22.1, "Виробництво гумових виробів");
insert into business_type(code_kved, title) values(22.11, "Виробництво гумових шин, покришок і камер; відновлення протектора гумових шин і покришок");
insert into business_type(code_kved, title) values(22.19, "Виробництво інших гумових виробів");
insert into business_type(code_kved, title) values(22.2, "Виробництво пластмасових виробів");
insert into business_type(code_kved, title) values(22.21, "Виробництво плит, листів, труб і профілів із пластмас");
insert into business_type(code_kved, title) values(22.22, "Виробництво тари з пластмас");
insert into business_type(code_kved, title) values(22.23, "Виробництво будівельних виробів із пластмас");
insert into business_type(code_kved, title) values(22.29, "Виробництво інших виробів із пластмас");
insert into business_type(code_kved, title) values(23, "Виробництво іншої неметалевої мінеральної продукції");
insert into business_type(code_kved, title) values(23.1, "Виробництво скла та виробів зі скла");
insert into business_type(code_kved, title) values(23.11, "Виробництво листового скла");
insert into business_type(code_kved, title) values(23.12, "Формування й оброблення листового скла");
insert into business_type(code_kved, title) values(23.13, "Виробництво порожнистого скла");
insert into business_type(code_kved, title) values(23.14, "Виробництво скловолокна");
insert into business_type(code_kved, title) values(23.19, "Виробництво й оброблення інших скляних виробів, у тому числі технічних");
insert into business_type(code_kved, title) values(23.2, "Виробництво вогнетривких виробів");
insert into business_type(code_kved, title) values(23.3, "Виробництво будівельних матеріалів із глини");
insert into business_type(code_kved, title) values(23.31, "Виробництво керамічних плиток і плит");
insert into business_type(code_kved, title) values(23.32, "Виробництво цегли, черепиці та інших будівельних виробів із випаленої глини");
insert into business_type(code_kved, title) values(23.4, "Виробництво іншої продукції з фарфору та кераміки");
insert into business_type(code_kved, title) values(23.41, "Виробництво господарських і декоративних керамічних виробів");
insert into business_type(code_kved, title) values(23.42, "Виробництво керамічних санітарно-технічних виробів");
insert into business_type(code_kved, title) values(23.43, "Виробництво керамічних електроізоляторів та ізоляційної арматури");
insert into business_type(code_kved, title) values(23.44, "Виробництво інших керамічних виробів технічного призначення");
insert into business_type(code_kved, title) values(23.49, "Виробництво інших керамічних виробів");
insert into business_type(code_kved, title) values(23.5, "Виробництво цементу, вапна та гіпсових сумішей");
insert into business_type(code_kved, title) values(23.51, "Виробництво цементу");
insert into business_type(code_kved, title) values(23.52, "Виробництво вапна та гіпсових сумішей");
insert into business_type(code_kved, title) values(23.6, "Виготовлення виробів із бетону, гіпсу та цементу");
insert into business_type(code_kved, title) values(23.61, "Виготовлення виробів із бетону для будівництва");
insert into business_type(code_kved, title) values(23.62, "Виготовлення виробів із гіпсу для будівництва");
insert into business_type(code_kved, title) values(23.63, "Виробництво бетонних розчинів, готових для використання");
insert into business_type(code_kved, title) values(23.64, "Виробництво сухих будівельних сумішей");
insert into business_type(code_kved, title) values(23.65, "Виготовлення виробів із волокнистого цементу");
insert into business_type(code_kved, title) values(23.69, "Виробництво інших виробів із бетону гіпсу та цементу");
insert into business_type(code_kved, title) values(23.7, "Різання, оброблення та оздоблення декоративного та будівельного каменю");
insert into business_type(code_kved, title) values(23.9, "Виробництво абразивних виробів і неметалевих мінеральних виробів, н. в. і. у.");
insert into business_type(code_kved, title) values(23.91, "Виробництво абразивних виробів");
insert into business_type(code_kved, title) values(23.99, "Виробництво неметалевих мінеральних виробів, н. в. і. у.");
insert into business_type(code_kved, title) values(24, "Металургійне виробництво");
insert into business_type(code_kved, title) values(24.1, "Виробництво чавуну, сталі та феросплавів");
insert into business_type(code_kved, title) values(24.2, "Виробництво труб, порожнистих профілів і фітингів зі сталі");
insert into business_type(code_kved, title) values(24.3, "Виробництво іншої продукції первинного оброблення сталі");
insert into business_type(code_kved, title) values(24.31, "Холодне волочіння прутків і профілів");
insert into business_type(code_kved, title) values(24.32, "Холодний прокат вузької штаби");
insert into business_type(code_kved, title) values(24.33, "Холодне штампування та гнуття");
insert into business_type(code_kved, title) values(24.34, "Холодне волочіння дроту");
insert into business_type(code_kved, title) values(24.4, "Виробництво дорогоцінних та інших кольорових металів");
insert into business_type(code_kved, title) values(24.41, "Виробництво дорогоцінних металів");
insert into business_type(code_kved, title) values(24.42, "Виробництво алюмінію");
insert into business_type(code_kved, title) values(24.43, "Виробництво свинцю, цинку й олова");
insert into business_type(code_kved, title) values(24.44, "Виробництво міді");
insert into business_type(code_kved, title) values(24.45, "Виробництво інших кольорових металів");
insert into business_type(code_kved, title) values(24.46, "Виробництво ядерних матеріалів");
insert into business_type(code_kved, title) values(24.5, "Лиття металів");
insert into business_type(code_kved, title) values(24.51, "Лиття чавуну");
insert into business_type(code_kved, title) values(24.52, "Лиття сталі");
insert into business_type(code_kved, title) values(24.53, "Лиття легких кольорових металів");
insert into business_type(code_kved, title) values(24.54, "Лиття інших кольорових металів");
insert into business_type(code_kved, title) values(25, "Виробництво готових металевих виробів, крім машин і устатковання");
insert into business_type(code_kved, title) values(25.1, "Виробництво будівельних металевих конструкцій і виробів");
insert into business_type(code_kved, title) values(25.11, "Виробництво будівельних металевих конструкцій і частин конструкцій");
insert into business_type(code_kved, title) values(25.12, "Виробництво металевих дверей і вікон");
insert into business_type(code_kved, title) values(25.2, "Виробництво металевих баків, резервуарів і контейнерів");
insert into business_type(code_kved, title) values(25.21, "Виробництво радіаторів і котлів центрального опалення");
insert into business_type(code_kved, title) values(25.29, "Виробництво інших металевих баків, резервуарів і контейнерів");
insert into business_type(code_kved, title) values(25.3, "Виробництво парових котлів, крім котлів центрального опалення");
insert into business_type(code_kved, title) values(25.4, "Виробництво зброї та боєприпасів");
insert into business_type(code_kved, title) values(25.5, "Кування, пресування, штампування, профілювання; порошкова металургія");
insert into business_type(code_kved, title) values(25.6, "Оброблення металів та нанесення покриття на метали; механічне оброблення металевих виробів");
insert into business_type(code_kved, title) values(25.61, "Оброблення металів та нанесення покриття на метали");
insert into business_type(code_kved, title) values(25.62, "Механічне оброблення металевих виробів");
insert into business_type(code_kved, title) values(25.7, "Виробництво столових приборів, інструментів і металевих виробів загального призначення");
insert into business_type(code_kved, title) values(25.71, "Виробництво столових приборів");
insert into business_type(code_kved, title) values(25.72, "Виробництво замків і дверних петель");
insert into business_type(code_kved, title) values(25.73, "Виробництво інструментів");
insert into business_type(code_kved, title) values(25.9, "Виробництво інших готових металевих виробів");
insert into business_type(code_kved, title) values(25.91, "Виробництво сталевих бочок і подібних контейнерів");
insert into business_type(code_kved, title) values(25.92, "Виробництво легких металевих паковань");
insert into business_type(code_kved, title) values(25.93, "Виробництво виробів із дроту, ланцюгів і пружин");
insert into business_type(code_kved, title) values(25.94, "Виробництво кріпильних і ґвинтонарізних виробів");
insert into business_type(code_kved, title) values(25.99, "Виробництво інших готових металевих виробів, н. в. і. у.");
insert into business_type(code_kved, title) values(26, "Виробництво комп'ютерів, електронної та оптичної продукції");
insert into business_type(code_kved, title) values(26.1, "Виробництво електронних компонентів і плат");
insert into business_type(code_kved, title) values(26.11, "Виробництво електронних компонентів");
insert into business_type(code_kved, title) values(26.12, "Виробництво змонтованих електронних плат");
insert into business_type(code_kved, title) values(26.2, "Виробництво комп'ютерів і периферійного устатковання");
insert into business_type(code_kved, title) values(26.3, "Виробництво обладнання зв'язку");
insert into business_type(code_kved, title) values(26.4, "Виробництво електронної апаратури побутового призначення для приймання, записування та відтворювання звуку й зображення");
insert into business_type(code_kved, title) values(26.5, "Виробництво інструментів і обладнання для вимірювання, дослідження та навігації; виробництво годинників");
insert into business_type(code_kved, title) values(26.51, "Виробництво інструментів і обладнання для вимірювання, дослідження та навігації");
insert into business_type(code_kved, title) values(26.52, "Виробництво годинників");
insert into business_type(code_kved, title) values(26.6, "Виробництво радіологічного, електромедичного й електротерапевтичного устатковання");
insert into business_type(code_kved, title) values(26.7, "Виробництво оптичних приладів і фотографічного устатковання");
insert into business_type(code_kved, title) values(26.8, "Виробництво магнітних і оптичних носіїв даних");
insert into business_type(code_kved, title) values(27, "Виробництво електричного устатковання");
insert into business_type(code_kved, title) values(27.1, "Виробництво електродвигунів, генераторів, трансформаторів, електророзподільчої та контрольної апаратури");
insert into business_type(code_kved, title) values(27.11, "Виробництво електродвигунів, генераторів і трансформаторів");
insert into business_type(code_kved, title) values(27.12, "Виробництво електророзподільчої та контрольної апаратури");
insert into business_type(code_kved, title) values(27.2, "Виробництво батарей і акумуляторів");
insert into business_type(code_kved, title) values(27.3, "Виробництво проводів, кабелів і електромонтажних пристроїв");
insert into business_type(code_kved, title) values(27.31, "Виробництво волоконно-оптичних кабелів");
insert into business_type(code_kved, title) values(27.32, "Виробництво інших видів електронних і електричних проводів і кабелів");
insert into business_type(code_kved, title) values(27.33, "Виробництво електромонтажних пристроїв");
insert into business_type(code_kved, title) values(27.4, "Виробництво електричного освітлювального устатковання");
insert into business_type(code_kved, title) values(27.5, "Виробництво побутових приладів");
insert into business_type(code_kved, title) values(27.51, "Виробництво електричних побутових приладів");
insert into business_type(code_kved, title) values(27.52, "Виробництво неелектричних побутових приладів");
insert into business_type(code_kved, title) values(27.9, "Виробництво іншого електричного устатковання");
insert into business_type(code_kved, title) values(28, "Виробництво машин і устатковання, н. в. і. у.");
insert into business_type(code_kved, title) values(28.1, "Виробництво машин і устатковання загального призначення");
insert into business_type(code_kved, title) values(28.11, "Виробництво двигунів і турбін, крім авіаційних, автотранспортних і мотоциклетних двигунів");
insert into business_type(code_kved, title) values(28.12, "Виробництво гідравлічного та пневматичного устатковання");
insert into business_type(code_kved, title) values(28.13, "Виробництво інших помп і компресорів");
insert into business_type(code_kved, title) values(28.14, "Виробництво інших кранів і клапанів");
insert into business_type(code_kved, title) values(28.15, "Виробництво підшипників, зубчастих передач, елементів механічних передач і приводів");
insert into business_type(code_kved, title) values(28.2, "Виробництво інших машин і устатковання загального призначення");
insert into business_type(code_kved, title) values(28.21, "Виробництво печей і пічних пальників");
insert into business_type(code_kved, title) values(28.22, "Виробництво підіймального та вантажно-розвантажувального устатковання");
insert into business_type(code_kved, title) values(28.23, "Виробництво офісних машин і устатковання, крім комп'ютерів і периферійного устатковання");
insert into business_type(code_kved, title) values(28.24, "Виробництво ручних електромеханічних і пневматичних інструментів");
insert into business_type(code_kved, title) values(28.25, "Виробництво промислового холодильного та вентиляційного устатковання");
insert into business_type(code_kved, title) values(28.29, "Виробництво інших машин і устатковання загального призначення, н. в. і. у.");
insert into business_type(code_kved, title) values(28.3, "Виробництво машин і устатковання для сільського та лісового господарства");
insert into business_type(code_kved, title) values(28.4, "Виробництво металообробних машин і верстатів");
insert into business_type(code_kved, title) values(28.41, "Виробництво металообробних машин");
insert into business_type(code_kved, title) values(28.49, "Виробництво інших верстатів");
insert into business_type(code_kved, title) values(28.9, "Виробництво інших машин і устатковання спеціального призначення");
insert into business_type(code_kved, title) values(28.91, "Виробництво машин і устатковання для металургії");
insert into business_type(code_kved, title) values(28.92, "Виробництво машин і устатковання для добувної промисловості та будівництва");
insert into business_type(code_kved, title) values(28.93, "Виробництво машин і устатковання для виготовлення харчових продуктів і напоїв, перероблення тютюну");
insert into business_type(code_kved, title) values(28.94, "Виробництво машин і устатковання для виготовлення текстильних, швейних, хутряних і шкіряних виробів");
insert into business_type(code_kved, title) values(28.95, "Виробництво машин і устатковання для виготовлення паперу та картону");
insert into business_type(code_kved, title) values(28.96, "Виробництво машин і устатковання для виготовлення пластмас і гуми");
insert into business_type(code_kved, title) values(28.99, "Виробництво інших машин і устатковання спеціального призначення, н. в. і. у.");
insert into business_type(code_kved, title) values(29, "Виробництво автотранспортних засобів, причепів і напівпричепів");
insert into business_type(code_kved, title) values(29.1, "Виробництво автотранспортних засобів");
insert into business_type(code_kved, title) values(29.2, "Виробництво кузовів для автотранспортних засобів, причепів і напівпричепів");
insert into business_type(code_kved, title) values(29.3, "Виробництво вузлів, деталей і приладдя для автотранспортних засобів");
insert into business_type(code_kved, title) values(29.31, "Виробництво електричного й електронного устатковання для автотранспортних засобів");
insert into business_type(code_kved, title) values(29.32, "Виробництво інших вузлів, деталей і приладдя для автотранспортних засобів");
insert into business_type(code_kved, title) values(03.11, "Морське рибальство");
insert into business_type(code_kved, title) values(03.12, "Прісноводне рибальство");
insert into business_type(code_kved, title) values(03.21, "Морське рибництво (аквакультура)");
insert into business_type(code_kved, title) values(03.22, "Прісноводне рибництво (аквакультура)");
insert into business_type(code_kved, title) values(30, "Виробництво інших транспортних засобів");
insert into business_type(code_kved, title) values(30.1, "Будування суден і човнів");
insert into business_type(code_kved, title) values(30.11, "Будування суден і плавучих конструкцій");
insert into business_type(code_kved, title) values(30.12, "Будування прогулянкових і спортивних човнів");
insert into business_type(code_kved, title) values(30.2, "Виробництво залізничних локомотивів і рухомого складу");
insert into business_type(code_kved, title) values(30.3, "Виробництво повітряних і космічних літальних апаратів, супутнього устатковання");
insert into business_type(code_kved, title) values(30.4, "Виробництво військових транспортних засобів");
insert into business_type(code_kved, title) values(30.9, "Виробництво транспортних засобів, н. в. і. у.");
insert into business_type(code_kved, title) values(30.91, "Виробництво мотоциклів");
insert into business_type(code_kved, title) values(30.92, "Виробництво велосипедів, дитячих та інвалідних колясок");
insert into business_type(code_kved, title) values(30.99, "Виробництво інших транспортних засобів і обладнання, н. в. і. у.");
insert into business_type(code_kved, title) values(31.0, "Виробництво меблів");
insert into business_type(code_kved, title) values(31.01, "Виробництво меблів для офісів і підприємств торгівлі");
insert into business_type(code_kved, title) values(31.02, "Виробництво кухонних меблів");
insert into business_type(code_kved, title) values(31.03, "Виробництво матраців");
insert into business_type(code_kved, title) values(31.09, "Виробництво інших меблів");
insert into business_type(code_kved, title) values(32, "Виробництво іншої продукції");
insert into business_type(code_kved, title) values(32.1, "Виробництво ювелірних виробів, біжутерії та подібних виробів");
insert into business_type(code_kved, title) values(32.11, "Карбування монет");
insert into business_type(code_kved, title) values(32.12, "Виробництво ювелірних і подібних виробів");
insert into business_type(code_kved, title) values(32.13, "Виробництво біжутерії та подібних виробів");
insert into business_type(code_kved, title) values(32.2, "Виробництво музичних інструментів");
insert into business_type(code_kved, title) values(32.3, "Виробництво спортивних товарів");
insert into business_type(code_kved, title) values(32.4, "Виробництво ігор та іграшок");
insert into business_type(code_kved, title) values(32.5, "Виробництво медичних і стоматологічних інструментів і матеріалів");
insert into business_type(code_kved, title) values(32.9, "Виробництво продукції, н. в. і. у.");
insert into business_type(code_kved, title) values(32.91, "Виробництво мітел і щіток");
insert into business_type(code_kved, title) values(32.99, "Виробництво іншої продукції, н. в. і. у.");
insert into business_type(code_kved, title) values(33, "Ремонт і монтаж машин і устатковання");
insert into business_type(code_kved, title) values(33.1, "Ремонт і технічне обслуговування готових металевих виробів, машин і устатковання");
insert into business_type(code_kved, title) values(33.11, "Ремонт і технічне обслуговування готових металевих виробів");
insert into business_type(code_kved, title) values(33.12, "Ремонт і технічне обслуговування машин і устатковання промислового призначення");
insert into business_type(code_kved, title) values(33.13, "Ремонт і технічне обслуговування електронного й оптичного устатковання");
insert into business_type(code_kved, title) values(33.14, "Ремонт і технічне обслуговування електричного устатковання");
insert into business_type(code_kved, title) values(33.15, "Ремонт і технічне обслуговування суден і човнів");
insert into business_type(code_kved, title) values(33.16, "Ремонт і технічне обслуговування повітряних і космічних літальних апаратів");
insert into business_type(code_kved, title) values(33.17, "Ремонт і технічне обслуговування інших транспортних засобів");
insert into business_type(code_kved, title) values(33.19, "Ремонт і технічне обслуговування інших машин і устатковання");
insert into business_type(code_kved, title) values(33.2, "Установлення та монтаж машин і устатковання");
insert into business_type(code_kved, title) values(35, "Постачання електроенергії, газу, пари та кондиційованого повітря");
insert into business_type(code_kved, title) values(35.1, "Виробництво, передача та розподілення електроенергії");
insert into business_type(code_kved, title) values(35.11, "Виробництво електроенергії");
insert into business_type(code_kved, title) values(35.12, "Передача електроенергії");
insert into business_type(code_kved, title) values(35.13, "Розподілення електроенергії");
insert into business_type(code_kved, title) values(35.14, "Торгівля електроенергією");
insert into business_type(code_kved, title) values(35.2, "Виробництво газу; розподілення газоподібного палива через місцеві (локальні) трубопроводи");
insert into business_type(code_kved, title) values(35.21, "Виробництво газу");
insert into business_type(code_kved, title) values(35.22, "Розподілення газоподібного палива через місцеві (локальні) трубопроводи");
insert into business_type(code_kved, title) values(35.23, "Торгівля газом через місцеві (локальні) трубопроводи");
insert into business_type(code_kved, title) values(35.3, "Постачання пари, гарячої води та кондиційованого повітря");
insert into business_type(code_kved, title) values(36.0, "Забір, очищення та постачання води");
insert into business_type(code_kved, title) values(37.0, "Каналізація, відведення й очищення стічних вод");
insert into business_type(code_kved, title) values(38, "Збирання, оброблення й видалення відходів; відновлення матеріалів");
insert into business_type(code_kved, title) values(38.1, "Збирання відходів");
insert into business_type(code_kved, title) values(38.11, "Збирання безпечних відходів");
insert into business_type(code_kved, title) values(38.12, "Збирання небезпечних відходів");
insert into business_type(code_kved, title) values(38.2, "Оброблення та видалення відходів");
insert into business_type(code_kved, title) values(38.21, "Оброблення та видалення безпечних відходів");
insert into business_type(code_kved, title) values(38.22, "Оброблення та видалення небезпечних відходів");
insert into business_type(code_kved, title) values(38.3, "Відновлення матеріалів");
insert into business_type(code_kved, title) values(38.31, "Демонтаж (розбирання) машин і устатковання");
insert into business_type(code_kved, title) values(38.32, "Відновлення відсортованих відходів");
insert into business_type(code_kved, title) values(39.0, "Інша діяльність щодо поводження з відходами");
insert into business_type(code_kved, title) values(41, "Будівництво будівель");
insert into business_type(code_kved, title) values(41.1, "Організація будівництва будівель");
insert into business_type(code_kved, title) values(41.2, "Будівництво житлових і нежитлових будівель");
insert into business_type(code_kved, title) values(42, "Будівництво споруд");
insert into business_type(code_kved, title) values(42.1, "Будівництво доріг і залізниць");
insert into business_type(code_kved, title) values(42.11, "Будівництво доріг і автострад");
insert into business_type(code_kved, title) values(42.12, "Будівництво залізниць і метрополітену");
insert into business_type(code_kved, title) values(42.13, "Будівництво мостів і тунелів");
insert into business_type(code_kved, title) values(42.2, "Будівництво комунікацій");
insert into business_type(code_kved, title) values(42.21, "Будівництво трубопроводів");
insert into business_type(code_kved, title) values(42.22, "Будівництво споруд електропостачання та телекомунікацій");
insert into business_type(code_kved, title) values(42.9, "Будівництво інших споруд");
insert into business_type(code_kved, title) values(42.91, "Будівництво водних споруд");
insert into business_type(code_kved, title) values(42.99, "Будівництво інших споруд, н. в. і. у.");
insert into business_type(code_kved, title) values(43, "Спеціалізовані будівельні роботи");
insert into business_type(code_kved, title) values(43.1, "Знесення та підготовчі роботи на будівельному майданчику");
insert into business_type(code_kved, title) values(43.11, "Знесення");
insert into business_type(code_kved, title) values(43.12, "Підготовчі роботи на будівельному майданчику");
insert into business_type(code_kved, title) values(43.13, "Розвідувальне буріння");
insert into business_type(code_kved, title) values(43.2, "Електромонтажні, водопровідні та інші будівельно-монтажні роботи");
insert into business_type(code_kved, title) values(43.21, "Електромонтажні роботи");
insert into business_type(code_kved, title) values(43.22, "Монтаж водопровідних мереж, систем опалення та кондиціонування");
insert into business_type(code_kved, title) values(43.29, "Інші будівельно-монтажні роботи");
insert into business_type(code_kved, title) values(43.3, "Роботи із завершення будівництва");
insert into business_type(code_kved, title) values(43.31, "Штукатурні роботи");
insert into business_type(code_kved, title) values(43.32, "Установлення столярних виробів");
insert into business_type(code_kved, title) values(43.33, "Покриття підлоги й облицювання стін");
insert into business_type(code_kved, title) values(43.34, "Малярні роботи та скління");
insert into business_type(code_kved, title) values(43.39, "Інші роботи із завершення будівництва");
insert into business_type(code_kved, title) values(43.9, "Інші спеціалізовані будівельні роботи");
insert into business_type(code_kved, title) values(43.91, "Покрівельні роботи");
insert into business_type(code_kved, title) values(43.99, "Інші спеціалізовані будівельні роботи, н. в. і. у.");
insert into business_type(code_kved, title) values(45, "Оптова та роздрібна торгівля автотранспортними засобами та мотоциклами, їх ремонт");
insert into business_type(code_kved, title) values(45.1, "Торгівля автотранспортними засобами");
insert into business_type(code_kved, title) values(45.11, "Торгівля автомобілями та легковими автотранспортними засобами");
insert into business_type(code_kved, title) values(45.19, "Торгівля іншими автотранспортними засобами");
insert into business_type(code_kved, title) values(45.2, "Технічне обслуговування та ремонт автотранспортних засобів");
insert into business_type(code_kved, title) values(45.3, "Торгівля деталями та приладдям для автотранспортних засобів");
insert into business_type(code_kved, title) values(45.31, "Оптова торгівля деталями та приладдям для автотранспортних засобів");
insert into business_type(code_kved, title) values(45.32, "Роздрібна торгівля деталями та приладдям для автотранспортних засобів");
insert into business_type(code_kved, title) values(45.4, "Торгівля мотоциклами, деталями та приладдям до них, технічне обслуговування і ремонт мотоциклів");
insert into business_type(code_kved, title) values(46, "Оптова торгівля, крім торгівлі автотранспортними засобами та мотоциклами");
insert into business_type(code_kved, title) values(46.1, "Оптова торгівля за винагороду чи на основі контракту");
insert into business_type(code_kved, title) values(46.11, "Діяльність посередників у торгівлі сільськогосподарською сировиною, живими тваринами, текстильною сировиною та напівфабрикатами");
insert into business_type(code_kved, title) values(46.12, "Діяльність посередників у торгівлі паливом, рудами, металами та промисловими хімічними речовинами");
insert into business_type(code_kved, title) values(46.13, "Діяльність посередників у торгівлі деревиною, будівельними матеріалами та санітарно-технічними виробами");
insert into business_type(code_kved, title) values(46.14, "Діяльність посередників у торгівлі машинами, промисловим устаткованням, суднами та літаками");
insert into business_type(code_kved, title) values(46.15, "Діяльність посередників у торгівлі меблями, господарськими товарами, залізними та іншими металевими виробами");
insert into business_type(code_kved, title) values(46.16, "Діяльність посередників у торгівлі текстильними виробами, одягом, хутром, взуттям і шкіряними виробами");
insert into business_type(code_kved, title) values(46.17, "Діяльність посередників у торгівлі продуктами харчування, напоями та тютюновими виробами");
insert into business_type(code_kved, title) values(46.18, "Діяльність посередників, що спеціалізуються в торгівлі іншими товарами");
insert into business_type(code_kved, title) values(46.19, "Діяльність посередників у торгівлі товарами широкого асортименту");
insert into business_type(code_kved, title) values(46.2, "Оптова торгівля сільськогосподарською сировиною та живими тваринами");
insert into business_type(code_kved, title) values(46.21, "Оптова торгівля зерном, необробленим тютюном, насінням і кормами для тварин");
insert into business_type(code_kved, title) values(46.22, "Оптова торгівля квітами та рослинами");
insert into business_type(code_kved, title) values(46.23, "Оптова торгівля живими тваринами");
insert into business_type(code_kved, title) values(46.24, "Оптова торгівля шкірсировиною, шкурами та шкірою");
insert into business_type(code_kved, title) values(46.3, "Оптова торгівля продуктами харчування, напоями та тютюновими виробами");
insert into business_type(code_kved, title) values(46.31, "Оптова торгівля фруктами й овочами");
insert into business_type(code_kved, title) values(46.32, "Оптова торгівля м'ясом і м'ясними продуктами");
insert into business_type(code_kved, title) values(46.33, "Оптова торгівля молочними продуктами, яйцями, харчовими оліями та жирами");
insert into business_type(code_kved, title) values(46.34, "Оптова торгівля напоями");
insert into business_type(code_kved, title) values(46.35, "Оптова торгівля тютюновими виробами");
insert into business_type(code_kved, title) values(46.36, "Оптова торгівля цукром, шоколадом і кондитерськими виробами");
insert into business_type(code_kved, title) values(46.37, "Оптова торгівля кавою, чаєм, какао та прянощами");
insert into business_type(code_kved, title) values(46.38, "Оптова торгівля іншими продуктами харчування, у тому числі рибою, ракоподібними та молюсками");
insert into business_type(code_kved, title) values(46.39, "Неспеціалізована оптова торгівля продуктами харчування, напоями та тютюновими виробами");
insert into business_type(code_kved, title) values(46.4, "Оптова торгівля товарами господарського призначення");
insert into business_type(code_kved, title) values(46.41, "Оптова торгівля текстильними товарами");
insert into business_type(code_kved, title) values(46.42, "Оптова торгівля одягом і взуттям");
insert into business_type(code_kved, title) values(46.43, "Оптова торгівля побутовими електротоварами й електронною апаратурою побутового призначення для приймання, записування, відтворювання звуку й зображення");
insert into business_type(code_kved, title) values(46.44, "Оптова торгівля фарфором, скляним посудом і засобами для чищення");
insert into business_type(code_kved, title) values(46.45, "Оптова торгівля парфумними та косметичними товарами");
insert into business_type(code_kved, title) values(46.46, "Оптова торгівля фармацевтичними товарами");
insert into business_type(code_kved, title) values(46.47, "Оптова торгівля меблями, килимами й освітлювальним приладдям");
insert into business_type(code_kved, title) values(46.48, "Оптова торгівля годинниками та ювелірними виробами");
insert into business_type(code_kved, title) values(46.49, "Оптова торгівля іншими товарами господарського призначення");
insert into business_type(code_kved, title) values(46.5, "Оптова торгівля інформаційним і комунікаційним устаткованням");
insert into business_type(code_kved, title) values(46.51, "Оптова торгівля комп'ютерами, периферійним устаткованням і програмним забезпеченням");
insert into business_type(code_kved, title) values(46.52, "Оптова торгівля електронним і телекомунікаційним устаткованням, деталями до нього");
insert into business_type(code_kved, title) values(46.6, "Оптова торгівля іншими машинами й устаткованням");
insert into business_type(code_kved, title) values(46.61, "Оптова торгівля сільськогосподарськими машинами й устаткованням");
insert into business_type(code_kved, title) values(46.62, "Оптова торгівля верстатами");
insert into business_type(code_kved, title) values(46.63, "Оптова торгівля машинами й устаткованням для добувної промисловості та будівництва");
insert into business_type(code_kved, title) values(46.64, "Оптова торгівля машинами й устаткованням для текстильного, швейного та трикотажного виробництва");
insert into business_type(code_kved, title) values(46.65, "Оптова торгівля офісними меблями");
insert into business_type(code_kved, title) values(46.66, "Оптова торгівля іншими офісними машинами й устаткованням");
insert into business_type(code_kved, title) values(46.69, "Оптова торгівля іншими машинами та устаткованням");
insert into business_type(code_kved, title) values(46.7, "Інші види спеціалізованої оптової торгівлі");
insert into business_type(code_kved, title) values(46.71, "Оптова торгівля твердим, рідким, газоподібним паливом і подібними продуктами");
insert into business_type(code_kved, title) values(46.72, "Оптова торгівля металами та металевими рудами");
insert into business_type(code_kved, title) values(46.73, "Оптова торгівля деревиною, будівельними матеріалами та санітарно-технічним обладнанням");
insert into business_type(code_kved, title) values(46.74, "Оптова торгівля залізними виробами, водопровідним і опалювальним устаткованням і приладдям до нього");
insert into business_type(code_kved, title) values(46.75, "Оптова торгівля хімічними продуктами");
insert into business_type(code_kved, title) values(46.76, "Оптова торгівля іншими проміжними продуктами");
insert into business_type(code_kved, title) values(46.77, "Оптова торгівля відходами та брухтом");
insert into business_type(code_kved, title) values(46.9, "Неспеціалізована оптова торгівля");
insert into business_type(code_kved, title) values(47, "Роздрібна торгівля, крім торгівлі автотранспортними засобами та мотоциклами");
insert into business_type(code_kved, title) values(47.1, "Роздрібна торгівля в неспеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.11, "Роздрібна торгівля в неспеціалізованих магазинах переважно продуктами харчування, напоями та тютюновими виробами");
insert into business_type(code_kved, title) values(47.19, "Інші види роздрібної торгівлі в неспеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.2, "Роздрібна торгівля продуктами харчування, напоями та тютюновими виробами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.21, "Роздрібна торгівля фруктами й овочами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.22, "Роздрібна торгівля м'ясом і м'ясними продуктами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.23, "Роздрібна торгівля рибою, ракоподібними та молюсками в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.24, "Роздрібна торгівля хлібобулочними виробами, борошняними та цукровими кондитерськими виробами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.25, "Роздрібна торгівля напоями в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.26, "Роздрібна торгівля тютюновими виробами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.29, "Роздрібна торгівля іншими продуктами харчування в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.3, "Роздрібна торгівля пальним");
insert into business_type(code_kved, title) values(47.4, "Роздрібна торгівля інформаційним і комунікаційним устаткованням у спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.41, "Роздрібна торгівля комп'ютерами, периферійним устаткованням і програмним забезпеченням у спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.42, "Роздрібна торгівля телекомунікаційним устаткованням у спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.43, "Роздрібна торгівля в спеціалізованих магазинах електронною апаратурою побутового призначення для приймання, записування, відтворення звуку й зображення");
insert into business_type(code_kved, title) values(47.5, "Роздрібна торгівля іншими товарами господарського призначення в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.51, "Роздрібна торгівля текстильними товарами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.52, "Роздрібна торгівля залізними виробами, будівельними матеріалами та санітарно-технічними виробами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.53, "Роздрібна торгівля килимами, килимовими виробами, покриттям для стін і підлоги в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.54, "Роздрібна торгівля побутовими електротоварами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.59, "Роздрібна торгівля меблями, освітлювальним приладдям та іншими товарами для дому в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.6, "Роздрібна торгівля товарами культурного призначення та товарами для відпочинку в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.61, "Роздрібна торгівля книгами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.62, "Роздрібна торгівля газетами та канцелярськими товарами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.63, "Роздрібна торгівля аудіо- та відеозаписами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.64, "Роздрібна торгівля спортивним інвентарем у спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.65, "Роздрібна торгівля іграми та іграшками в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.7, "Роздрібна торгівля іншими товарами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.71, "Роздрібна торгівля одягом у спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.72, "Роздрібна торгівля взуттям і шкіряними виробами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.73, "Роздрібна торгівля фармацевтичними товарами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.74, "Роздрібна торгівля медичними й ортопедичними товарами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.75, "Роздрібна торгівля косметичними товарами та туалетними приналежностями в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.76, "Роздрібна торгівля квітами, рослинами, насінням, добривами, домашніми тваринами та кормами для них у спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.77, "Роздрібна торгівля годинниками та ювелірними виробами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.78, "Роздрібна торгівля іншими невживаними товарами в спеціалізованих магазинах");
insert into business_type(code_kved, title) values(47.79, "Роздрібна торгівля уживаними товарами в магазинах");
insert into business_type(code_kved, title) values(47.8, "Роздрібна торгівля з лотків і на ринках");
insert into business_type(code_kved, title) values(47.81, "Роздрібна торгівля з лотків і на ринках харчовими продуктами, напоями та тютюновими виробами");
insert into business_type(code_kved, title) values(47.82, "Роздрібна торгівля з лотків і на ринках текстильними виробами, одягом і взуттям");
insert into business_type(code_kved, title) values(47.89, "Роздрібна торгівля з лотків і на ринках іншими товарами");
insert into business_type(code_kved, title) values(47.9, "Роздрібна торгівля поза магазинами");
insert into business_type(code_kved, title) values(47.91, "Роздрібна торгівля, що здійснюється фірмами поштового замовлення або через мережу Інтернет");
insert into business_type(code_kved, title) values(47.99, "Інші види роздрібної торгівлі поза магазинами");
insert into business_type(code_kved, title) values(49, "Наземний і трубопровідний транспорт");
insert into business_type(code_kved, title) values(49.1, "Пасажирський залізничний транспорт міжміського сполучення");
insert into business_type(code_kved, title) values(49.2, "Вантажний залізничний транспорт");
insert into business_type(code_kved, title) values(49.3, "Інший пасажирський наземний транспорт");
insert into business_type(code_kved, title) values(49.31, "Пасажирський наземний транспорт міського та приміського сполучення");
insert into business_type(code_kved, title) values(49.32, "Надання послуг таксі");
insert into business_type(code_kved, title) values(49.39, "Інший пасажирський наземний транспорт, н. в. і. у.");
insert into business_type(code_kved, title) values(49.4, "Вантажний автомобільний транспорт, надання послуг перевезення речей");
insert into business_type(code_kved, title) values(49.41, "Вантажний автомобільний транспорт");
insert into business_type(code_kved, title) values(49.42, "Надання послуг перевезення речей (переїзду)");
insert into business_type(code_kved, title) values(49.5, "Трубопровідний транспорт");
insert into business_type(code_kved, title) values(50, "Водний транспорт");
insert into business_type(code_kved, title) values(50.1, "Пасажирський морський транспорт");
insert into business_type(code_kved, title) values(50.2, "Вантажний морський транспорт");
insert into business_type(code_kved, title) values(50.3, "Пасажирський річковий транспорт");
insert into business_type(code_kved, title) values(50.4, "Вантажний річковий транспорт");
insert into business_type(code_kved, title) values(51, "Авіаційний транспорт");
insert into business_type(code_kved, title) values(51.1, "Пасажирський авіаційний транспорт");
insert into business_type(code_kved, title) values(51.2, "Вантажний авіаційний транспорт і космічний транспорт");
insert into business_type(code_kved, title) values(51.21, "Вантажний авіаційний транспорт");
insert into business_type(code_kved, title) values(51.22, "Космічний транспорт");
insert into business_type(code_kved, title) values(52, "Складське господарство та допоміжна діяльність у сфері транспорту");
insert into business_type(code_kved, title) values(52.1, "Складське господарство");
insert into business_type(code_kved, title) values(52.2, "Допоміжна діяльність у сфері транспорту");
insert into business_type(code_kved, title) values(52.21, "Допоміжне обслуговування наземного транспорту");
insert into business_type(code_kved, title) values(52.22, "Допоміжне обслуговування водного транспорту");
insert into business_type(code_kved, title) values(52.23, "Допоміжне обслуговування авіаційного транспорту");
insert into business_type(code_kved, title) values(52.24, "Транспортне оброблення вантажів");
insert into business_type(code_kved, title) values(52.29, "Інша допоміжна діяльність у сфері транспорту");
insert into business_type(code_kved, title) values(53, "Поштова та кур'єрська діяльність");
insert into business_type(code_kved, title) values(53.1, "Діяльність національної пошти");
insert into business_type(code_kved, title) values(53.2, "Інша поштова та кур'єрська діяльність");
insert into business_type(code_kved, title) values(55, "Тимчасове розміщування");
insert into business_type(code_kved, title) values(55.1, "Діяльність готелів і подібних засобів тимчасового розміщування");
insert into business_type(code_kved, title) values(55.2, "Діяльність засобів розміщування на період відпустки та іншого тимчасового проживання");
insert into business_type(code_kved, title) values(55.3, "Надання місць кемпінгами та стоянками для житлових автофургонів і причепів");
insert into business_type(code_kved, title) values(55.9, "Діяльність інших засобів тимчасового розміщування");
insert into business_type(code_kved, title) values(56, "Діяльність із забезпечення стравами та напоями");
insert into business_type(code_kved, title) values(56.1, "Діяльність ресторанів, надання послуг мобільного харчування");
insert into business_type(code_kved, title) values(56.2, "Постачання готових страв");
insert into business_type(code_kved, title) values(56.21, "Постачання готових страв для подій");
insert into business_type(code_kved, title) values(56.29, "Постачання інших готових страв");
insert into business_type(code_kved, title) values(56.3, "Обслуговування напоями");
insert into business_type(code_kved, title) values(58, "Видавнича діяльність");
insert into business_type(code_kved, title) values(58.1, "Видання книг, періодичних видань та інша видавнича діяльність");
insert into business_type(code_kved, title) values(58.11, "Видання книг");
insert into business_type(code_kved, title) values(58.12, "Видання довідників і каталогів");
insert into business_type(code_kved, title) values(58.13, "Видання газет");
insert into business_type(code_kved, title) values(58.14, "Видання журналів і періодичних видань");
insert into business_type(code_kved, title) values(58.19, "Інші види видавничої діяльності");
insert into business_type(code_kved, title) values(58.2, "Видання програмного забезпечення");
insert into business_type(code_kved, title) values(58.21, "Видання комп'ютерних ігор");
insert into business_type(code_kved, title) values(58.29, "Видання іншого програмного забезпечення");
insert into business_type(code_kved, title) values(59, "Виробництво кіно-та відеофільмів, телевізійних програм, видання звукозаписів");
insert into business_type(code_kved, title) values(59.11, "Виробництво кіно- та відеофільмів, телевізійних програм");
insert into business_type(code_kved, title) values(59.12, "Компонування кіно- та відеофільмів, телевізійних програм");
insert into business_type(code_kved, title) values(59.13, "Розповсюдження кіно- та відеофільмів, телевізійних програм");
insert into business_type(code_kved, title) values(59.14, "Демонстрація кінофільмів");
insert into business_type(code_kved, title) values(59.2, "Видання звукозаписів");
insert into business_type(code_kved, title) values(60, "Діяльність у сфері радіомовлення та телевізійного мовлення");
insert into business_type(code_kved, title) values(60.1, "Діяльність у сфері радіомовлення");
insert into business_type(code_kved, title) values(60.2, "Діяльність у сфері телевізійного мовлення");
insert into business_type(code_kved, title) values(61, "Телекомунікації (електрозв'язок)");
insert into business_type(code_kved, title) values(61.1, "Діяльність у сфері проводового електрозв'язку");
insert into business_type(code_kved, title) values(61.2, "Діяльність у сфері безпроводового електрозв'язку");
insert into business_type(code_kved, title) values(61.3, "Діяльність у сфері супутникового електрозв'язку");
insert into business_type(code_kved, title) values(61.9, "Інша діяльність у сфері електрозв'язку");
insert into business_type(code_kved, title) values(62.0, "Комп'ютерне програмування, консультування та пов'язана з ними діяльність");
insert into business_type(code_kved, title) values(62.01, "Комп'ютерне програмування");
insert into business_type(code_kved, title) values(62.02, "Консультування з питань інформатизації");
insert into business_type(code_kved, title) values(62.03, "Діяльність із керування комп'ютерним устаткованням");
insert into business_type(code_kved, title) values(62.09, "Інша діяльність у сфері інформаційних технологій і комп'ютерних систем");
insert into business_type(code_kved, title) values(63, "Надання інформаційних послуг");
insert into business_type(code_kved, title) values(63.1, "Оброблення даних, розміщення інформації на веб-вузлах і пов'язана з ними діяльність; веб-портали");
insert into business_type(code_kved, title) values(63.11, "Оброблення даних, розміщення інформації на веб-вузлах і пов'язана з ними діяльність");
insert into business_type(code_kved, title) values(63.12, "Веб-портали");
insert into business_type(code_kved, title) values(63.9, "Надання інших інформаційних послуг");
insert into business_type(code_kved, title) values(63.91, "Діяльність інформаційних агентств");
insert into business_type(code_kved, title) values(63.99, "Надання інших інформаційних послуг, н. в. і. у.");
insert into business_type(code_kved, title) values(64, "Надання фінансових послуг, крім страхування та пенсійного забезпечення");
insert into business_type(code_kved, title) values(64.1, "Грошове посередництво");
insert into business_type(code_kved, title) values(64.11, "Діяльність центрального банку");
insert into business_type(code_kved, title) values(64.19, "Інші види грошового посередництва");
insert into business_type(code_kved, title) values(64.2, "Діяльність холдингових компаній");
insert into business_type(code_kved, title) values(64.3, "Трасти, фонди та подібні фінансові суб'єкти");
insert into business_type(code_kved, title) values(64.9, "Надання інших фінансових послуг, крім страхування та пенсійного забезпечення");
insert into business_type(code_kved, title) values(64.91, "Фінансовий лізинг");
insert into business_type(code_kved, title) values(64.92, "Інші види кредитування");
insert into business_type(code_kved, title) values(64.99, "Надання інших фінансових послуг (крім страхування та пенсійного забезпечення), н. в. і. у.");
insert into business_type(code_kved, title) values(65, "Страхування, перестрахування та недержавне пенсійне забезпечення, крім обов'язкового соціального страхування");
insert into business_type(code_kved, title) values(65.1, "Страхування");
insert into business_type(code_kved, title) values(65.11, "Страхування життя");
insert into business_type(code_kved, title) values(65.12, "Інші види страхування, крім страхування життя");
insert into business_type(code_kved, title) values(65.2, "Перестрахування");
insert into business_type(code_kved, title) values(65.3, "Недержавне пенсійне забезпечення");
insert into business_type(code_kved, title) values(66, "Допоміжна діяльність у сферах фінансових послуг і страхування");
insert into business_type(code_kved, title) values(66.1, "Допоміжна діяльність у сфері фінансових послуг, крім страхування та пенсійного забезпечення");
insert into business_type(code_kved, title) values(66.11, "Управління фінансовими ринками");
insert into business_type(code_kved, title) values(66.12, "Посередництво за договорами по цінних паперах або товарах");
insert into business_type(code_kved, title) values(66.19, "Інша допоміжна діяльність у сфері фінансових послуг, крім страхування та пенсійного забезпечення");
insert into business_type(code_kved, title) values(66.2, "Допоміжна діяльність у сфері страхування та пенсійного забезпечення");
insert into business_type(code_kved, title) values(66.21, "Оцінювання ризиків та завданої шкоди");
insert into business_type(code_kved, title) values(66.22, "Діяльність страхових агентів і брокерів");
insert into business_type(code_kved, title) values(66.29, "Інша допоміжна діяльність у сфері страхування та пенсійного забезпечення");
insert into business_type(code_kved, title) values(66.3, "Управління фондами");
insert into business_type(code_kved, title) values(68, "Операції з нерухомим майном");
insert into business_type(code_kved, title) values(68.1, "Купівля та продаж власного нерухомого майна");
insert into business_type(code_kved, title) values(68.2, "Надання в оренду й експлуатацію власного чи орендованого нерухомого майна");
insert into business_type(code_kved, title) values(68.3, "Операції з нерухомим майном за винагороду або на основі контракту");
insert into business_type(code_kved, title) values(68.31, "Агентства нерухомості");
insert into business_type(code_kved, title) values(68.32, "Управління нерухомим майном за винагороду або на основі контракту");
insert into business_type(code_kved, title) values(69, "Діяльність у сферах права та бухгалтерського обліку");
insert into business_type(code_kved, title) values(69.1, "Діяльність у сфері права");
insert into business_type(code_kved, title) values(69.2, "Діяльність у сфері бухгалтерського обліку й аудиту; консультування з питань оподаткування");
insert into business_type(code_kved, title) values(07.21, "Добування уранових і торієвих руд");
insert into business_type(code_kved, title) values(07.29, "Добування руд інших кольорових металів");
insert into business_type(code_kved, title) values(70, "Діяльність головних управлінь (хед-офісів); консультування з питань керування");
insert into business_type(code_kved, title) values(70.1, "Діяльність головних управлінь (хед-офісів)");
insert into business_type(code_kved, title) values(70.2, "Консультування з питань керування");
insert into business_type(code_kved, title) values(70.21, "Діяльність у сфері зв'язків із громадськістю");
insert into business_type(code_kved, title) values(70.22, "Консультування з питань комерційної діяльності й керування");
insert into business_type(code_kved, title) values(71, "Діяльність у сферах архітектури та інжинірингу; технічні випробування та дослідження");
insert into business_type(code_kved, title) values(71.1, "Діяльність у сферах архітектури та інжинірингу, надання послуг технічного консультування");
insert into business_type(code_kved, title) values(71.11, "Діяльність у сфері архітектури");
insert into business_type(code_kved, title) values(71.12, "Діяльність у сфері інжинірингу, геології та геодезії, надання послуг технічного консультування в цих сферах");
insert into business_type(code_kved, title) values(71.2, "Технічні випробування та дослідження");
insert into business_type(code_kved, title) values(72, "Наукові дослідження та розробки");
insert into business_type(code_kved, title) values(72.1, "Дослідження й експериментальні розробки у сфері природничих і технічних наук");
insert into business_type(code_kved, title) values(72.11, "Дослідження й експериментальні розробки у сфері біотехнологій");
insert into business_type(code_kved, title) values(72.19, "Дослідження й експериментальні розробки у сфері інших природничих і технічних наук");
insert into business_type(code_kved, title) values(72.2, "Дослідження й експериментальні розробки у сфері суспільних і гуманітарних наук");
insert into business_type(code_kved, title) values(73, "Рекламна діяльність і дослідження кон'юнктури ринку");
insert into business_type(code_kved, title) values(73.1, "Рекламна діяльність");
insert into business_type(code_kved, title) values(73.11, "Рекламні агентства");
insert into business_type(code_kved, title) values(73.12, "Посередництво в розміщенні реклами в засобах масової інформації");
insert into business_type(code_kved, title) values(73.2, "Дослідження кон'юнктури ринку та виявлення громадської думки");
insert into business_type(code_kved, title) values(74, "Інша професійна, наукова та технічна діяльність");
insert into business_type(code_kved, title) values(74.1, "Спеціалізована діяльність із дизайну");
insert into business_type(code_kved, title) values(74.2, "Діяльність у сфері фотографії");
insert into business_type(code_kved, title) values(74.3, "Надання послуг перекладу");
insert into business_type(code_kved, title) values(74.9, "Інша професійна, наукова та технічна діяльність, н. в. і. у.");
insert into business_type(code_kved, title) values(75.0, "Ветеринарна діяльність");
insert into business_type(code_kved, title) values(77, "Оренда, прокат і лізинг");
insert into business_type(code_kved, title) values(77.1, "Надання в оренду автотранспортних засобів");
insert into business_type(code_kved, title) values(77.11, "Надання в оренду автомобілів і легкових автотранспортних засобів");
insert into business_type(code_kved, title) values(77.12, "Надання в оренду вантажних автомобілів");
insert into business_type(code_kved, title) values(77.2, "Прокат побутових виробів і предметів особистого вжитку");
insert into business_type(code_kved, title) values(77.21, "Прокат товарів для спорту та відпочинку");
insert into business_type(code_kved, title) values(77.22, "Прокат відеозаписів і дисків");
insert into business_type(code_kved, title) values(77.29, "Прокат інших побутових виробів і предметів особистого вжитку");
insert into business_type(code_kved, title) values(77.3, "Надання в оренду інших машин, устатковання та товарів");
insert into business_type(code_kved, title) values(77.31, "Надання в оренду сільськогосподарських машин і устатковання");
insert into business_type(code_kved, title) values(77.32, "Надання в оренду будівельних машин і устатковання");
insert into business_type(code_kved, title) values(77.33, "Надання в оренду офісних машин і устатковання, у тому числі комп'ютерів");
insert into business_type(code_kved, title) values(77.34, "Надання в оренду водних транспортних засобів");
insert into business_type(code_kved, title) values(77.35, "Надання в оренду повітряних транспортних засобів");
insert into business_type(code_kved, title) values(77.39, "Надання в оренду інших машин, устатковання та товарів. н. в. і. у.");
insert into business_type(code_kved, title) values(77.4, "Лізинг інтелектуальної власності та подібних продуктів, крім творів, захищених авторськими правами");
insert into business_type(code_kved, title) values(78, "Діяльність із працевлаштування");
insert into business_type(code_kved, title) values(78.1, "Діяльність агентств працевлаштування");
insert into business_type(code_kved, title) values(78.2, "Діяльність агентств тимчасового працевлаштування");
insert into business_type(code_kved, title) values(78.3, "Інша діяльність із забезпечення трудовими ресурсами");
insert into business_type(code_kved, title) values(79, "Діяльність туристичних агентств, туристичних операторів, надання інших послуг бронювання та пов'язана з цим діяльність");
insert into business_type(code_kved, title) values(79.1, "Діяльність туристичних агентств і туристичних операторів");
insert into business_type(code_kved, title) values(79.11, "Діяльність туристичних агентств");
insert into business_type(code_kved, title) values(79.12, "Діяльність туристичних операторів");
insert into business_type(code_kved, title) values(79.9, "Надання інших послуг бронювання та пов'язана з цим діяльність");
insert into business_type(code_kved, title) values(08.11, "Добування декоративного та будівельного каменю, вапняку, гіпсу, крейди та глинистого сланцю");
insert into business_type(code_kved, title) values(08.12, "Добування піску, гравію, глин і каоліну");
insert into business_type(code_kved, title) values(08.91, "Добування мінеральної сировини для хімічної промисловості та виробництва мінеральних добрив");
insert into business_type(code_kved, title) values(08.92, "Добування торфу");
insert into business_type(code_kved, title) values(08.93, "Добування солі");
insert into business_type(code_kved, title) values(08.99, "Добування інших корисних копалин і розроблення кар'єрів, н. в. і. у.");
insert into business_type(code_kved, title) values(80, "Діяльність охоронних служб та проведення розслідувань");
insert into business_type(code_kved, title) values(80.1, "Діяльність приватних охоронних служб");
insert into business_type(code_kved, title) values(80.2, "Обслуговування систем безпеки");
insert into business_type(code_kved, title) values(80.3, "Проведення розслідувань");
insert into business_type(code_kved, title) values(81, "Обслуговування будинків і територій");
insert into business_type(code_kved, title) values(81.1, "Комплексне обслуговування об'єктів");
insert into business_type(code_kved, title) values(81.2, "Діяльність із прибирання");
insert into business_type(code_kved, title) values(81.21, "Загальне прибирання будинків");
insert into business_type(code_kved, title) values(81.22, "Інша діяльність із прибирання будинків і промислових об'єктів");
insert into business_type(code_kved, title) values(81.3, "Надання ландшафтних послуг");
insert into business_type(code_kved, title) values(82, "Адміністративна та допоміжна офісна діяльність, інші допоміжні комерційні послуги");
insert into business_type(code_kved, title) values(82.1, "Адміністративна та допоміжна офісна діяльність");
insert into business_type(code_kved, title) values(82.11, "Надання комбінованих офісних адміністративних послуг");
insert into business_type(code_kved, title) values(82.19, "Фотокопіювання, підготування документів та інша спеціалізована допоміжна офісна діяльність");
insert into business_type(code_kved, title) values(82.2, "Діяльність телефонних центрів");
insert into business_type(code_kved, title) values(82.3, "Організування конгресів і торговельних виставок");
insert into business_type(code_kved, title) values(82.9, "Надання допоміжних комерційних послуг, н. в. і. у.");
insert into business_type(code_kved, title) values(82.91, "Діяльність агентств зі стягування платежів і бюро кредитних історій");
insert into business_type(code_kved, title) values(82.92, "Пакування");
insert into business_type(code_kved, title) values(82.99, "Надання інших допоміжних комерційних послуг, н. в. і. у.");
insert into business_type(code_kved, title) values(84, "Державне управління й оборона; обов'язкове соціальне страхування");
insert into business_type(code_kved, title) values(84.1, "Державне управління загального характеру; соціально-економічне управління");
insert into business_type(code_kved, title) values(84.11, "Державне управління загального характеру");
insert into business_type(code_kved, title) values(84.12, "Регулювання у сферах охорони здоров'я, освіти, культури та інших соціальних сферах, крім обов'язкового соціального страхування");
insert into business_type(code_kved, title) values(84.13, "Регулювання та сприяння ефективному веденню економічної діяльності");
insert into business_type(code_kved, title) values(84.2, "Надання державних послуг суспільству в цілому");
insert into business_type(code_kved, title) values(84.21, "Міжнародна діяльність");
insert into business_type(code_kved, title) values(84.22, "Діяльність у сфері оборони");
insert into business_type(code_kved, title) values(84.23, "Діяльність у сфері юстиції та правосуддя");
insert into business_type(code_kved, title) values(84.24, "Діяльність у сфері охорони громадського порядку та безпеки");
insert into business_type(code_kved, title) values(84.25, "Діяльність пожежних служб");
insert into business_type(code_kved, title) values(84.3, "Діяльність у сфері обов'язкового соціального страхування");
insert into business_type(code_kved, title) values(85, "Освіта");
insert into business_type(code_kved, title) values(85.1, "Дошкільна освіта");
insert into business_type(code_kved, title) values(85.2, "Початкова освіта");
insert into business_type(code_kved, title) values(85.3, "Середня освіта");
insert into business_type(code_kved, title) values(85.31, "Загальна середня освіта");
insert into business_type(code_kved, title) values(85.32, "Професійно-технічна освіта");
insert into business_type(code_kved, title) values(85.41, "Професійно-технічна освіта на рівні вищого професійно-технічного навчального закладу");
insert into business_type(code_kved, title) values(85.42, "Вища освіта");
insert into business_type(code_kved, title) values(85.5, "Інші види освіти");
insert into business_type(code_kved, title) values(85.51, "Освіта у сфері спорту та відпочинку");
insert into business_type(code_kved, title) values(85.52, "Освіта у сфері культури");
insert into business_type(code_kved, title) values(85.53, "Діяльність шкіл підготовлення водіїв транспортних засобів");
insert into business_type(code_kved, title) values(85.59, "Інші види освіти, н. в. і. у.");
insert into business_type(code_kved, title) values(85.60, "Допоміжна діяльність у сфері освіти");
insert into business_type(code_kved, title) values(86, "Охорона здоров'я");
insert into business_type(code_kved, title) values(86.1, "Діяльність лікарняних закладів");
insert into business_type(code_kved, title) values(86.2, "Медична та стоматологічна практика");
insert into business_type(code_kved, title) values(86.21, "Загальна медична практика");
insert into business_type(code_kved, title) values(86.22, "Спеціалізована медична практика");
insert into business_type(code_kved, title) values(86.23, "Стоматологічна практика");
insert into business_type(code_kved, title) values(86.9, "Інша діяльність у сфері охорони здоров'я");
insert into business_type(code_kved, title) values(87, "Надання послуг догляду із забезпеченням проживання");
insert into business_type(code_kved, title) values(87.1, "Діяльність із догляду за хворими із забезпеченням проживання");
insert into business_type(code_kved, title) values(87.2, "Надання послуг догляду із забезпеченням проживання для осіб з розумовими вадами та хворих на наркоманію");
insert into business_type(code_kved, title) values(87.3, "Надання послуг догляду із забезпеченням проживання для осіб похилого віку та інвалідів");
insert into business_type(code_kved, title) values(87.9, "Надання інших послуг догляду із забезпеченням проживання");
insert into business_type(code_kved, title) values(88, "Надання соціальної допомоги без забезпечення проживання");
insert into business_type(code_kved, title) values(88.1, "Надання соціальної допомоги без забезпечення проживання для осіб похилого віку та інвалідів");
insert into business_type(code_kved, title) values(88.9, "Надання іншої соціальної допомоги без забезпечення проживання");
insert into business_type(code_kved, title) values(88.91, "Денний догляд за дітьми");
insert into business_type(code_kved, title) values(88.99, "Надання іншої соціальної допомоги без забезпечення проживання, н. в. і. у.");
insert into business_type(code_kved, title) values(90.0, "Діяльність у сфері творчості, мистецтва та розваг");
insert into business_type(code_kved, title) values(90.01, "Театральна та концертна діяльність");
insert into business_type(code_kved, title) values(90.02, "Діяльність щодо підтримання театральних і концертних заходів");
insert into business_type(code_kved, title) values(90.03, "Індивідуальна мистецька діяльність");
insert into business_type(code_kved, title) values(90.04, "Функціювання театральних і концертних залів");
insert into business_type(code_kved, title) values(91.0, "Функціювання бібліотек, архівів, музеїв та інших закладів культури");
insert into business_type(code_kved, title) values(91.01, "Функціювання бібліотек і архівів");
insert into business_type(code_kved, title) values(91.02, "Функціювання музеїв");
insert into business_type(code_kved, title) values(91.03, "Діяльність із охорони та використання пам'яток історії, будівель та інших пам'яток культури");
insert into business_type(code_kved, title) values(91.04, "Функціювання ботанічних садів, зоопарків і природних заповідників");
insert into business_type(code_kved, title) values(92.0, "Організування азартних ігор");
insert into business_type(code_kved, title) values(93, "Діяльність у сфері спорту, організування відпочинку та розваг");
insert into business_type(code_kved, title) values(93.1, "Діяльність у сфері спорту");
insert into business_type(code_kved, title) values(93.11, "Функціювання спортивних споруд");
insert into business_type(code_kved, title) values(93.12, "Діяльність спортивних клубів");
insert into business_type(code_kved, title) values(93.13, "Діяльність фітнес-центрів");
insert into business_type(code_kved, title) values(93.19, "Інша діяльність у сфері спорту");
insert into business_type(code_kved, title) values(93.2, "Організування відпочинку та розваг");
insert into business_type(code_kved, title) values(93.21, "Функціювання атракціонів і тематичних парків");
insert into business_type(code_kved, title) values(93.29, "Організування інших видів відпочинку та розваг");
insert into business_type(code_kved, title) values(94, "Діяльність громадських організацій");
insert into business_type(code_kved, title) values(94.1, "Діяльність організацій промисловців і підприємців, професійних організацій");
insert into business_type(code_kved, title) values(94.11, "Діяльність організацій промисловців і підприємців");
insert into business_type(code_kved, title) values(94.12, "Діяльність професійних громадських організацій");
insert into business_type(code_kved, title) values(94.2, "Діяльність професійних спілок");
insert into business_type(code_kved, title) values(94.9, "Діяльність інших громадських організацій");
insert into business_type(code_kved, title) values(94.91, "Діяльність релігійних організацій");
insert into business_type(code_kved, title) values(94.92, "Діяльність політичних організацій");
insert into business_type(code_kved, title) values(94.99, "Діяльність інших громадських організацій, н. в. і. у.");
insert into business_type(code_kved, title) values(95, "Ремонт комп'ютерів, побутових виробів і предметів особистого вжитку");
insert into business_type(code_kved, title) values(95.1, "Ремонт комп'ютерів і обладнання зв'язку");
insert into business_type(code_kved, title) values(95.11, "Ремонт комп'ютерів і периферійного устатковання");
insert into business_type(code_kved, title) values(95.12, "Ремонт обладнання зв'язку");
insert into business_type(code_kved, title) values(95.2, "Ремонт побутових виробів і предметів особистого вжитку");
insert into business_type(code_kved, title) values(95.21, "Ремонт електронної апаратури побутового призначення для приймання, записування, відтворення звуку й зображення");
insert into business_type(code_kved, title) values(95.22, "Ремонт побутових приладів, домашнього та садового обладнання");
insert into business_type(code_kved, title) values(95.23, "Ремонт взуття та шкіряних виробів");
insert into business_type(code_kved, title) values(95.24, "Ремонт меблів і домашнього начиння");
insert into business_type(code_kved, title) values(95.25, "Ремонт годинників і ювелірних виробів");
insert into business_type(code_kved, title) values(95.29, "Ремонт інших побутових виробів і предметів особистого вжитку");
insert into business_type(code_kved, title) values(96.0, "Надання інших індивідуальних послуг");
insert into business_type(code_kved, title) values(96.01, "Прання та хімічне чищення текстильних і хутряних виробів");
insert into business_type(code_kved, title) values(96.02, "Надання послуг перукарнями та салонами краси");
insert into business_type(code_kved, title) values(96.03, "Організування поховань і надання суміжних послуг");
insert into business_type(code_kved, title) values(96.04, "Діяльність із забезпечення фізичного комфорту");
insert into business_type(code_kved, title) values(96.09, "Надання інших індивідуальних послуг, н. в. і. у.");
insert into business_type(code_kved, title) values(97.0, "Діяльність домашніх господарств як роботодавців для домашньої прислуги");
insert into business_type(code_kved, title) values(98, "Діяльність домашніх господарств як виробників товарів та послуг для власного споживання");
insert into business_type(code_kved, title) values(98.1, "Діяльність домашніх господарств як виробників товарів для власного споживання");
insert into business_type(code_kved, title) values(98.2, "Діяльність домашніх господарств як виробників послуг для власного споживання");
insert into business_type(code_kved, title) values(99.0, "Діяльність екстериторіальних організацій і органів");