DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
  id       BIGINT          AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS role;

CREATE TABLE ROLE
(
  id   BIGINT       AUTO_INCREMENT,
  role VARCHAR(250) NOT NULL ,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS user_roles;

CREATE TABLE USER_ROLES (
  user_id BIGINT NOT NULL ,
  role_id BIGINT NOT NULL,
  FOREIGN KEY (role_id) REFERENCES ROLE (id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (user_id) REFERENCES USER (id) ON DELETE CASCADE ON UPDATE CASCADE
);

